apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gemgarden-wordpress
resources:
  - namespace.yaml
  - wp-config.yaml
  - pvc.yaml
  - seed-job.yaml
  - deployment.yaml
  - service.yaml