version: 2
updates:
  - package-ecosystem: helm
    directory: "/02.tailscale-operator"
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(deps)"
    groups:
      tailscale-operator:
        patterns:
          - "tailscale-operator"
  - package-ecosystem: helm
    directory: "/03.longhorn"
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(deps)"
    groups:
      longhorn:
        patterns:
          - "longhorn"
  - package-ecosystem: helm
    directory: "/99.apps/gatus"
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(deps)"
    groups:
      gatus:
        patterns:
          - "gatus"
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "main"
    schedule:
      interval: monthly
      day: saturday
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(deps)"
    groups:
      github-actions:
        patterns:
          - "*"
