apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: keycloak-k8s-resources
  namespace: flux-system
spec:
  url: https://github.com/keycloak/keycloak-k8s-resources
  ref:
    tag: 26.7.1
  interval: 1h