apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    tailscale.com/proxy-group: private-ingress-proxies
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - longhorn
  rules:
    - http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: longhorn-frontend
              port:
                number: 80
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-balanced-locality
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  replicaAutoBalance: "least-effort"
  dataLocality: "best-effort"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
