apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dozzle-data
  labels:
    app.kubernetes.io/name: dozzle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
