apiVersion: v1
kind: Service
metadata:
  name: dozzle
  labels:
    app.kubernetes.io/name: dozzle
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dozzle
