apiVersion: v2
name: longhorn-release
description: Home-lab umbrella chart for Longhorn
type: application
version: 0.1.0
dependencies:
  - name: longhorn
    version: 1.11.1
    repository: https://charts.longhorn.io
