apiVersion: v2
name: gatus-release
description: Home-lab umbrella chart for Gatus
type: application
version: 0.1.0
appVersion: "v5.34.0"
dependencies:
  - name: gatus
    version: 1.5.0
    repository: https://twin.github.io/helm-charts